# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/FPU/vivado_project/FPU1.srcs/sources_1/ip/fsqrt_double/fsqrt_double.xci
# IP: The module: 'fsqrt_double' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/FPU/vivado_project/FPU1.gen/sources_1/ip/fsqrt_double/fsqrt_double_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fsqrt_double'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: e:/FPU/vivado_project/FPU1.srcs/sources_1/ip/fsqrt_double/fsqrt_double.xci
# IP: The module: 'fsqrt_double' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/FPU/vivado_project/FPU1.gen/sources_1/ip/fsqrt_double/fsqrt_double_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fsqrt_double'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
