# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/FPU/vivado_project/FPU1.srcs/sources_1/ip/fmul_single/fmul_single.xci
# IP: The module: 'fmul_single' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/FPU/vivado_project/FPU1.gen/sources_1/ip/fmul_single/fmul_single_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fmul_single'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: e:/FPU/vivado_project/FPU1.srcs/sources_1/ip/fmul_single/fmul_single.xci
# IP: The module: 'fmul_single' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/FPU/vivado_project/FPU1.gen/sources_1/ip/fmul_single/fmul_single_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fmul_single'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
