# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Desktop/files/JYD/FPU/FPU1/FPU1/FPU1.srcs/sources_1/i/fcvt_s_wu/fcvt_s_wu.xci
# IP: The module: 'fcvt_s_wu' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Desktop/files/JYD/FPU/FPU1/FPU1/FPU1.srcs/sources_1/i/fcvt_s_wu/fcvt_s_wu_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fcvt_s_wu'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/Desktop/files/JYD/FPU/FPU1/FPU1/FPU1.srcs/sources_1/i/fcvt_s_wu/fcvt_s_wu.xci
# IP: The module: 'fcvt_s_wu' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Desktop/files/JYD/FPU/FPU1/FPU1/FPU1.srcs/sources_1/i/fcvt_s_wu/fcvt_s_wu_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fcvt_s_wu'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
