# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/FPU/vivado_project/FPU1.srcs/sources_1/ip/fcvt_s_wu/fcvt_s_wu.xci
# IP: The module: 'fcvt_s_wu' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/FPU/vivado_project/FPU1.gen/sources_1/ip/fcvt_s_wu/fcvt_s_wu_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fcvt_s_wu'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: e:/FPU/vivado_project/FPU1.srcs/sources_1/ip/fcvt_s_wu/fcvt_s_wu.xci
# IP: The module: 'fcvt_s_wu' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/FPU/vivado_project/FPU1.gen/sources_1/ip/fcvt_s_wu/fcvt_s_wu_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fcvt_s_wu'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
