# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Desktop/files/JYD/FPU/FPU1/FPU1/FPU1.srcs/sources_1/i/fadd_single/fadd_single.xci
# IP: The module: 'fadd_single' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Desktop/files/JYD/FPU/FPU1/FPU1/FPU1.srcs/sources_1/i/fadd_single/fadd_single_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fadd_single'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/Desktop/files/JYD/FPU/FPU1/FPU1/FPU1.srcs/sources_1/i/fadd_single/fadd_single.xci
# IP: The module: 'fadd_single' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Desktop/files/JYD/FPU/FPU1/FPU1/FPU1.srcs/sources_1/i/fadd_single/fadd_single_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fadd_single'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
